/**
 * App-level types: settings and the song index (PLAN §4, §9).
 */
import type { KeyBindings } from '../input/types.ts';

export interface Settings {
  bindings: KeyBindings;
  /** ms, screen vs audio. */
  audioOffset: number;
  /** ms, input latency. */
  inputOffset: number;
  /** Multiplier on scroll speed; 1 = default lead time. */
  hiSpeed: number;
  theme: 'dark' | 'light';
  hitSoundVolume: number;
  /** Set after the calibration screen has been completed at least once. */
  calibrated: boolean;
}

export const DEFAULT_SETTINGS: Settings = {
  bindings: { KL: 'KeyZ', KR: 'Comma', DL: 'KeyX', DR: 'KeyM' },
  audioOffset: 0,
  inputOffset: 0,
  hiSpeed: 1,
  theme: 'dark',
  hitSoundVolume: 0.8,
  calibrated: false,
};

/**
 * Difficulty tiers. A song folder holds up to one chart per tier
 * (songs-src/<id>/easy.osu, normal.osu, hard.osu → public/songs/<id>/chart.<tier>.json).
 */
export const TIERS = ['easy', 'normal', 'hard'] as const;
export type Tier = (typeof TIERS)[number];

/** Display names for the tier tiles (the user chose these spellings). */
export const TIER_LABEL: Record<Tier, string> = { easy: 'EASY', normal: 'NORMAL', hard: 'HARD' };

/** public/songs/<id>/meta.json */
export interface SongMeta {
  id: string;
  title: string;
  artist: string;
  /** Hex colours extracted from the jacket at build time, dominant first. */
  palette: string[];
  /** ms, per-song correction (normally 0). */
  audioOffset: number;
  /** Source audio length, ms (from the WAV header at build time). */
  durationMs: number;
  /** Where the song-select preview starts, ms: just before the densest stretch of the hardest chart. */
  previewMs: number;
  /** Content-hashed file names relative to the song folder. */
  audio: string;
  jacket: string;
  jacketSm: string;
  /** Sorted easy → normal → hard; a song may lack tiers. */
  charts: SongChartRef[];
}

export interface SongChartRef {
  tier: Tier;
  /** The .osu [Metadata] Version string, shown next to the tier. */
  name: string;
  /** File relative to the song folder, e.g. chart.hard.json */
  file: string;
  hash: string;
  od: number;
  /** [min, max] BPM. */
  bpm: [number, number];
  notes: number;
  /** osu!taiko star rating from rosu-pp at build time (no mods), 2 decimals. */
  stars: number;
  /**
   * 1–10, shown on the tier tile. Deterministic from the star rating at build
   * time: clamp(1, 10, round(stars × 1.6)) — Kantan ~2★ → 3, Oni ~4.5★ → 7, 6★+ → 10.
   */
  level: number;
}

/** public/songs/index.json, generated by tools/build-songs.ts */
export interface SongIndex {
  version: 1;
  songs: SongMeta[];
}
